Update products
removes stdin check and adds pivnet token check

diff --git a/scripts/products b/scripts/products
--- a/scripts/products
+++ b/scripts/products
@@ -1,5 +1,11 @@
 #!/bin/bash
 set -e
-cat > /dev/null
+
+# we must use stderr for error messages
+if [[ -z "${PIVNET_TOKEN}" ]]; then
+  >&2 echo "PIVNET_TOKEN environment variable is required"
+  exit 1
+fi
+
 pivnet login --api-token ${PIVNET_TOKEN} > /dev/null
 pivnet products --format=json
